1. Double-Checked Cancellation
	coroutines have special handling for cancellation exceptions, treating them as normal terminations instead of errors
	Problem: a cancellation exception thrown from code in a normal active coroutine can still cause the coroutine
		to terminate silently
	=> the coroutine vanishes abruptly and silently mid-way through its execution, even though nobody asked for it to 
		be stopped
	if the exception wasnâ€™t caused by a normal cancellation of the current coroutine, it must have been caused by some 
		other problem, which will now go completely undetected
	If the coroutine wasn't actually canceled, but some other code mistakenly threw a CancellationException, 
		rethrowing it could cause unintended silent termination
	=> If the coroutine was indeed canceled -> rethrowing CancellationException
	=> Before rethrowing a CancellationException, check if the coroutine was actually canceled using isActive
	Solution: whenever you see a cancellation exception, check whether the coroutine has actually been cancelled or not
	
	If a cancellation exception winds up being thrown from the try section, the explicit call to ensureActive 
		constitutes the second check for cancellation
	If the current job really is cancelled, the second check will immediately throw another cancellation exception, 
		breaking out of the catch block
	=> include a call to ensureActive at the top of the catch block