1. CancellationException is not a typical failure but a control mechanism, it should be rethrown to allow proper 
	coroutine behavior.

2. modularization
	seperation of concerns
	avoid merge conflicts
	improve code reusability and testability
	optimize the dependency graph for better build time
	3 module: feature modules, library modules and app modules

3. Goodbye try-catch, Hello runCatching
	onFailure, onSuccess
	handle recoverable failures explicitly by returning a value, such as using Result<T>, rather than throwing exceptions
	=> failure handling clearer and avoids unexpected disruptions in execution flow
	A popular functional programming library, Arrow [2], provides Either, which similarly encapsulates success and failure
	runCatching function, which automatically catches exceptions and wraps them in a Result

	Using runCatching as a scope function (like run) 
	=> encapsulates both computation and error handling within a single block, reducing boilerplate

	Replacing Try-Catch with an Empty Catch Block: use getOrElse {}
	Rethrow Original Exceptions with a getOrThrow
	Handling Nested Exceptions with runCatching
		With runCatching in combination with mapCatching error handling is more structured and concise.
	Replacing Try-Catch-Finally Blocks: use 'use' block

	Handling Coroutines and Errors with runCatching

4. A shallow copy creates a new object that is a copy of the original object, but it does not create new copies of any 
	nested objects
	Instead, the new object contains references to the same nested objects as the original
	copy() in data class

5. A deep copy, on the other hand, creates a new object and recursively copies all nested objects
	To implement a deep copy in Kotlin, you typically need to override the clone() method (in Clonable) or use 
	serialization techniques